- name: create kcp dir
  file:
    path: "{{kcp_path}}"
    state: directory

# download if not exists
- name: check if kcp is installed
  stat: path="{{kcp_path}}/{{kcp_bin}}"
  register: p_kcp
- name: install kcp
  unarchive: src={{kcp_download_url}} dest={{kcp_path}} remote_src=True
  when: p_kcp.stat.exists is defined and not p_kcp.stat.exists

- name: make kcp an service
  template:
    src: "kcp.service.j2"
    dest: "/etc/systemd/system/kcp.service"
- name: start kcp
  service: name=kcp state=restarted enabled=true
      
