- name: create kcp dir
  file:
    path: "{{kcp_path}}/{{kcp_version}}"
    state: directory

# download if not exists
- name: check if kcp is installed
  stat: path="{{kcp_path}}/{{kcp_version}}/{{kcp_bin}}"
  register: p_kcp

- name: install kcp
  unarchive:
    src: "https://github.com/xtaci/kcptun/releases/download/v{{kcp_version}}/kcptun-linux-{{kcp_arch}}-{{kcp_version}}.tar.gz"
    dest: "{{kcp_path}}/{{kcp_version}}"
    remote_src: True
  when: p_kcp.stat.exists is defined and not p_kcp.stat.exists

- import_role:
    name: halida.cmd_service
  vars:
    name: kcp
    cmd: "{{kcp_path}}/{{kcp_version}}/{{kcp_bin}} -t '127.0.0.1:{{ss_port}}' -l ':{{kcp_port}}' -key '{{kcp_password}}' -mtu 1400 -sndwnd 2048 -rcvwnd 2048 -mode fast2"
