# ss
# - name: ss repo
#   apt_repository:
#     repo: "ppa:max-c-lv/shadowsocks-libev"

- name: install ss
  apt:
    name: shadowsocks-libev

- import_role:
    name: halida.cmd_service
  vars:
    name: ss
    cmd: "/usr/bin/ss-server -p {{ss_port}} -k '{{ss_password}}' -m chacha20-ietf-poly1305"
