# ss

- name: install ss
  apt:
    name: shadowsocks-libev

- ansible.builtin.systemd_service:
    name: shadowsocks-libev
    enabled: false

- import_role:
    name: halida.cmd_service
  vars:
    name: ss
    cmd: "/usr/bin/ss-server -p {{ss_port}} -k '{{ss_password}}' -m chacha20-ietf-poly1305"
